import images from "./images";

const movies = [
  {
    _id: "1",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "33 слова о дизайне",
    image: images.movie01,
    duration: 147,
  },
  {
    _id: "2",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Киноальманах «100 лет дизайна»",
    image: images.movie02,
    duration: 147,
  },
  {
    _id: "3",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "В погоне за Бенкси",
    image: images.movie03,
    duration: 147,
  },
  {
    _id: "4",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Баския: Взрыв реальности",
    image: images.movie04,
    duration: 147,
  },
  {
    _id: "5",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Баския: Взрыв реальности",
    image: images.movie05,
    duration: 147,
  },
  {
    _id: "6",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Книготорговцы",
    image: images.movie06,
    duration: 147,
  },
  {
    _id: "7",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Когда я думаю о Германии ночью",
    image: images.movie07,
    duration: 147,
  },
  {
    _id: "8",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Gimme Danger: История Игги и The Stooges",
    image: images.movie08,
    duration: 147,
  },
  {
    _id: "9",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Киноальманах «100 лет дизайна»",
    image: images.movie02,
    duration: 147,
  },
  {
    _id: "10",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "В погоне за Бенкси",
    image: images.movie03,
    duration: 147,
  },
  {
    _id: "11",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Баския: Взрыв реальности",
    image: images.movie04,
    duration: 147,
  },
  {
    _id: "12",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Баския: Взрыв реальности",
    image: images.movie05,
    duration: 147,
  },
  {
    _id: "13",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Книготорговцы",
    image: images.movie06,
    duration: 147,
  },
  {
    _id: "14",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Когда я думаю о Германии ночью",
    image: images.movie07,
    duration: 147,
  },
  {
    _id: "15",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Gimme Danger: История Игги и The Stooges",
    image: images.movie08,
    duration: 147,
  },
  {
    _id: "16",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "33 слова о дизайне",
    image: images.movie01,
    duration: 147,
  },
  {
    _id: "17",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "Gimme Danger: История Игги и The Stooges",
    image: images.movie08,
    duration: 147,
  },
  {
    _id: "18",
    trailer: "https://youtu.be/shW9i6k8cB0",
    title: "33 слова о дизайне",
    image: images.movie01,
    duration: 147,
  },
];

export default movies;
